spring.application.name=REST API Stud

# DataSource
spring.datasource.url=jdbc:postgresql://109.198.190.115:32322/EvsevevS?ssl=false
spring.datasource.username=student
spring.datasource.password=5432
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# use schema.sql and data.sql
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
spring.sql.init.data-locations=classpath:data.sql

# JWT
jwt.secret=mySuperSecretKeyForJWTGenerationWithAtLeast32BytesLength!
jwt.expiration=86400000

# Logging
logging.level.org.springframework.security=DEBUG